services:
  DatingLibre\CcBillBundle\Service\CcBillClientService:
    class: DatingLibre\CcBillBundle\Service\CcBillClientService
    public: true
    autowire: true
    autoconfigure: true
    arguments: [ '%datinglibre.ccbill_username%',
                 '%env(resolve:CCBILL_PASSWORD)%',
                 '%datinglibre.ccbill_client_account%',
                 '%datinglibre.ccbill_client_sub_account%' ]

  DatingLibre\CcBillBundle\Command\ViewSubscriptionStatus:
    class: DatingLibre\CcBillBundle\Command\ViewSubscriptionStatus
    tags:
      - { name: console.command }
      - { name: container.no_preload }
    autowire: true
    autoconfigure: true
    arguments: [ '@DatingLibre\CcBillBundle\Service\CcBillClientService' ]
    calls:
      - [ setName, [ 'app:ccbill:status' ] ]

  DatingLibre\CcBillBundle\Command\CancelSubscription:
    class: DatingLibre\CcBillBundle\Command\CancelSubscription
    tags:
      - { name: console.command }
      - { name: container.no_preload }
    autowire: true
    autoconfigure: true
    arguments: [ '@DatingLibre\CcBillBundle\Service\CcBillClientService' ]
    calls:
      - [ setName, [ 'app:ccbill:cancel' ] ]